name: Tweet Scheduler

on:
  schedule:
    # - cron: '0 */3 * * *'  # Every 3 hours; adjust as needed
    - cron: '*/1 * * * *'  # Every 1 minute

jobs:
  post_tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Tweepy
      run: |
        python -m pip install --upgrade pip
        pip install tweepy

    - name: Post Tweet
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        import os
        import tweepy

        # Authenticate to Twitter
        auth = tweepy.OAuthHandler(os.environ["TWITTER_API_KEY"], os.environ["TWITTER_API_SECRET"])
        auth.set_access_token(os.environ["TWITTER_ACCESS_TOKEN"], os.environ["TWITTER_ACCESS_TOKEN_SECRET"])
        api = tweepy.API(auth)

        # Load tweets from file
        with open('tweets.txt', 'r') as file:
            tweets = file.readlines()

        # Post first tweet and remove it from the file
        if tweets:
            tweet = tweets[0].strip()
            api.update_status(tweet)
            
            # Update the file to remove the posted tweet
            with open('tweets.txt', 'w') as file:
                file.writelines(tweets[1:])
